env_scripts = [
"""
#!@duckscript
if is_empty ${GW2_PATH}
    gw2_path = set "C:/Program Files/Guild Wars 2"

    steam_path = set "C:/Program Files (x86)/Steam/steamapps/common/Guild Wars 2"
    if is_path_exists ${steam_path}
        gw2_path = set ${steam_path}
    end

    set_env GW2_PATH ${gw2_path}
end
"""
]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["reffect"]
INSTALL_PATH = "${GW2_PATH}/addons"

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.copy-release]
script = "cp \"${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/release/${CARGO_MAKE_CRATE_NAME}.dll\" \"${INSTALL_PATH}\""
script_runner = "@shell"

[tasks.copy-release-update]
script = "cp \"${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/release/${CARGO_MAKE_CRATE_NAME}.dll\" \"${INSTALL_PATH}/${CARGO_MAKE_CRATE_NAME}.dll.update\""
script_runner = "@shell"

[tasks.copy-release-pdb]
script = "cp \"${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/release/${CARGO_MAKE_CRATE_NAME}.pdb\" \"${INSTALL_PATH}"
script_runner = "@shell"

[tasks.copy-debug]
script = "cp \"${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/${CARGO_MAKE_CRATE_NAME}.dll\" \"${INSTALL_PATH}/${CARGO_MAKE_CRATE_NAME}.dll.update\""
script_runner = "@shell"

[tasks.copy-debug-pdb]
script = "cp \"${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/${CARGO_MAKE_CRATE_NAME}.pdb\" \"${INSTALL_PATH}"
script_runner = "@shell"

[tasks.remove]
script = "rm \"${INSTALL_PATH}/${CARGO_MAKE_CRATE_NAME}.dll\""
script_runner = "@shell"

[tasks.install]
run_task = { name = ["build-release", "copy-release"] }

[tasks.install-examples]
script = "cp \"${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/examples/*\" \"${INSTALL_PATH}/reffect/packs\""
script_runner = "@shell"

[tasks.uninstall]
alias = "remove"

[tasks.dev-release]
run_task = { name = ["build-release", "copy-release-update", "copy-release-pdb"] }
watch = true

[tasks.dev]
run_task = { name = ["build", "copy-debug", "copy-debug-pdb"] }
watch = true
